name: Basic Workflow
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ci-main
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - name: Run a simple command
        run: echo "Hello from GitHub Actions!"
